
FROM jenkins/jenkins:lts

USER root
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get update --fix-missing && \
    apt-get install -y --no-install-recommends \
        make \
        g++ \
        curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER jenkins